name: jaibangla
description: "A new Flutter project"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8
  # ---------- State Management ----------
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  provider: ^6.1.2
  go_router: ^14.2.0

  # ---------- Networking & APIs ----------
  http: ^1.2.1
  dio: ^5.7.0
  connectivity_plus: ^6.0.3
  jwt_decoder: ^2.0.1

  # ---------- Storage ----------
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # ---------- UI / UX ----------
  intl: ^0.19.0
  lottie: ^3.1.2
  fluttertoast: ^8.2.5
  another_flushbar: ^1.12.30

  # ---------- Device Features ----------
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0

  # ---------- Firebase / Notifications ----------
  firebase_core: ^3.3.0
  firebase_messaging: ^15.1.3

  # ---------- Utilities ----------
  logger: ^2.4.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # ✅ Assets must be declared here
  assets:
    - assets/icons/
    - assets/splash/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/jai_bangla_app_logo.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/icons/jai_bangla_app_logo.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/app_splash_1.png
  android: true
  ios: true
  web: false
